@baseUrl = http://localhost:3001/api
@token = {{login.response.body.$.token}}
@tokenOther = {{loginOther.response.body.$.token}}
@blogId = {{createBlog.response.body.$.id}}

# @name getBlogs
GET {{baseUrl}}/blogs

###

# @name createBlog
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer {{token}}

{
    "author": "Test Author",
    "title": "Example Blog",
    "url": "https://example.com/",
    "year": 2023
}

###

# @name createBlog2
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: bearer {{tokenOther}}

{
    "author": "Another Author",
    "title": "Another Example",
    "url": "https://example.com/",
    "year": 2022
}

###

# @name getBlog
GET {{baseUrl}}/blogs/{{blogId}}

###

# @name getBlogSearchTest
GET {{baseUrl}}/blogs/?search=test

###

# @name getBlogSearchExample
GET {{baseUrl}}/blogs/?search=example

###

# @name setLikesZero
PUT {{baseUrl}}/blogs/{{blogId}}
Content-Type: application/json

{
    "likes": 0
}

###

# @name setLikesOne
PUT {{baseUrl}}/blogs/{{blogId}}
Content-Type: application/json

{
    "likes": 1
}

###

# @name deleteBlog
DELETE {{baseUrl}}/blogs/{{blogId}}
Authorization: bearer {{token}}


###

# @name deleteBlogOther
DELETE {{baseUrl}}/blogs/{{blogId}}
Authorization: bearer {{tokenOther}}

###


# @name createBlogTitleMissing
POST {{baseUrl}}/blogs HTTP/1.1
Authorization: bearer {{token}}
Content-Type: application/json

{
    "author": "Test Author",
    "url": "https://example.com/"
}

###

# @name setLikesNull
PUT {{baseUrl}}/blogs/{{blogId}}
Content-Type: application/json

{
    "likes": null
}

###


# @name getUsers
GET {{baseUrl}}/users

###

# @name getUser
GET {{baseUrl}}/users/1

###

# @name getUserRead
GET {{baseUrl}}/users/1?read=true

###

# @name getUserUnread
GET {{baseUrl}}/users/1?read=false

###

# @name getUserBadstate
GET {{baseUrl}}/users/1?read=other

###

# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "testuser@example.com",
    "name": "First Last"
}

###

# @name createUserOther
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "otheruser@example.com",
    "name": "First2 Last2"
}

###

# @name createUserNotEmail
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "testuser",
    "name": "First Last"
}

###

# @name login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "testuser@example.com",
  "password": "secret"
}

###

# @name loginOther
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "otheruser@example.com",
  "password": "secret"
}

###

# @name renameUser
PUT {{baseUrl}}/users/testuser@example.com
Authorization: bearer {{token}}

###

# @name renameUser2
PUT {{baseUrl}}/users/testuser2@example.com
Authorization: bearer {{token}}
 
###

# @name getAuthors
GET {{baseUrl}}/authors

###

# @name markRead
PUT {{baseUrl}}/readinglists/1
Authorization: bearer {{token}}
Content-Type: application/json

{
    "read": true
}

###

# @name markUnread
PUT {{baseUrl}}/readinglists/1
Authorization: bearer {{token}}
Content-Type: application/json

{
    "read": false
}
